export const TASK_EVENTS = {
  TASK_QUEUED: 'TASK_QUEUED',
  TASK_STARTED: 'TASK_STARTED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_FAILED: 'TASK_FAILED',
  TASK_CANCELLED: 'TASK_CANCELLED',
  TASK_RETRYING: 'TASK_RETRYING',
  TASK_TIMEOUT: 'TASK_TIMEOUT',

  ISSUE_PROCESSING_STARTED: 'ISSUE_PROCESSING_STARTED',

  CA_REQUESTED: 'CA_REQUESTED',
  CA_ALLOCATED: 'CA_ALLOCATED',
  CA_CREATED: 'CA_CREATED',
  CA_CONNECTED: 'CA_CONNECTED',
  CA_ERROR: 'CA_ERROR',
  CA_DESTROYED: 'CA_DESTROYED',
  CA_RELEASED: 'CA_RELEASED',
  CA_CHECK_COMPLETE: 'CA_CHECK_COMPLETE',

  CONTAINER_CREATING: 'CONTAINER_CREATING',
  CONTAINER_CREATED: 'CONTAINER_CREATED',
  CONTAINER_DELETING: 'CONTAINER_DELETING',
  CONTAINER_DELETED: 'CONTAINER_DELETED',
  CONTAINER_STARTING: 'CONTAINER_STARTING',
  CONTAINER_STARTED: 'CONTAINER_STARTED',
  CONTAINER_STOPPING: 'CONTAINER_STOPPING',
  CONTAINER_STOPPED: 'CONTAINER_STOPPED',
  CONTAINER_RESTARTING: 'CONTAINER_RESTARTING',
  CONTAINER_RESTARTED: 'CONTAINER_RESTARTED',
  CONTAINER_UPDATING: 'CONTAINER_UPDATING',
  CONTAINER_UPDATED: 'CONTAINER_UPDATED',
  CONTAINER_SYNCING: 'CONTAINER_SYNCING',
  CONTAINER_SYNCED: 'CONTAINER_SYNCED',
  CONTAINER_ERROR: 'CONTAINER_ERROR',

  AI_CODING_STARTED: 'AI_CODING_STARTED',
  AI_CODING_COMPLETE: 'AI_CODING_COMPLETE',
  AI_CODING_ERROR: 'AI_CODING_ERROR',

  PR_CREATED: 'PR_CREATED',
  PR_MERGED: 'PR_MERGED',
  PR_ERROR: 'PR_ERROR',

  ERROR_COMMENT_POSTED: 'ERROR_COMMENT_POSTED'
} as const;

export type TaskEventType = (typeof TASK_EVENTS)[keyof typeof TASK_EVENTS];
