export const TASK_EVENTS = {
  TASK_QUEUED: 'TASK_QUEUED',
  TASK_STARTED: 'TASK_STARTED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_FAILED: 'TASK_FAILED',
  TASK_CANCELLED: 'TASK_CANCELLED',
  TASK_RETRYING: 'TASK_RETRYING',
  TASK_TIMEOUT: 'TASK_TIMEOUT',

  CA_REQUESTED: 'CA_REQUESTED',
  CA_ALLOCATED: 'CA_ALLOCATED',
  CA_CREATED: 'CA_CREATED',
  CA_CONNECTED: 'CA_CONNECTED',
  CA_ERROR: 'CA_ERROR',
  CA_DESTROYED: 'CA_DESTROYED',
  CA_RELEASED: 'CA_RELEASED',
  CA_CHECK_COMPLETE: 'CA_CHECK_COMPLETE',

  AI_CODING_STARTED: 'AI_CODING_STARTED',
  AI_CODING_COMPLETE: 'AI_CODING_COMPLETE',
  AI_CODING_ERROR: 'AI_CODING_ERROR',

  PR_CREATED: 'PR_CREATED',
  PR_MERGED: 'PR_MERGED',
  PR_ERROR: 'PR_ERROR',

  ERROR_COMMENT_POSTED: 'ERROR_COMMENT_POSTED'
} as const;

export type TaskEventType = (typeof TASK_EVENTS)[keyof typeof TASK_EVENTS];
