export const TASK_CONSTANTS = {
  INITIAL_RETRY_DELAY: 10000,
  SECOND_RETRY_DELAY: 20000,
  FINAL_RETRY_DELAY: 40000,
  AI_CODING_TIMEOUT: 1800000
} as const;

export const TASK_CONFIG = {
  MAX_CA_COUNT: 3,
  CA_NAME_PREFIX: process.env.HRA_CA_NAME_PREFIX ?? 'hra_',

  MONITOR_INTERVAL: 30000,

  CA_STATUS_CHECK_ENABLED: true,
  CA_STATUS_CHECK_INTERVALS: [10000, 20000, 30000, 60000] as const,

  RETRY_DELAYS: [
    TASK_CONSTANTS.INITIAL_RETRY_DELAY,
    TASK_CONSTANTS.SECOND_RETRY_DELAY,
    TASK_CONSTANTS.FINAL_RETRY_DELAY
  ] as const,
  MAX_RETRY_COUNT: 5,

  TASK_TIMEOUT: 600000,
  AI_CODING_TIMEOUT: TASK_CONSTANTS.AI_CODING_TIMEOUT,

  LOG_DIR: process.env.TASK_LOG_DIR ?? './logs/tasks',
  LOG_LEVEL: process.env.LOG_LEVEL ?? 'info'
} as const;

export type RetryDelay = (typeof TASK_CONFIG.RETRY_DELAYS)[number];
